### ISSUE TITLE
Same production server for both classes (E-28 and E-15)?

### ISSUE THREAD

**Issue by kerynegan** [susanBuck/e28-spring21#10]
Hi Susan,

I think the answer is likely "yes, use the same domain," given how you had me set up my local folders etc., but I just wanted to confirm that there isn't any reason I shouldn't be able to use the same domain and production server/droplet for both E-28 and E-15 this term, with unique subdomains for the projects? So projects 1 for each would be:

- E15p1.myuniquedomain.me
- E28p1.myuniquedomain.me

And so on for the rest of the course? 

Thanks,
Keryn

**Comment by susanBuck** [comment]
You are correct - you can use the same domain. : )

**Comment by kerynegan** [comment]
Great, thank you!
