### ISSUE TITLE
Bad owner or permissions on C:\Users\YourName\.ssh\config - Alternative Solution

### ISSUE THREAD

**Issue by katz2row** [susanBuck/e28-spring21#11]
**Environment**
Command line - Specifically regarding SSH keys

**What operating system are you using?**
Windows 10 Pro

**Describe the problem**
After configuring the SSH keys, `Bad owner or permissions on C:\Users\YourName\.ssh\config` is returned when trying to test a connection.

**Steps taken**
After receiving the above message, I did some Googling. I found a couple useful GitHub issues threads. One actually linked to [a thread](https://github.com/susanBuck/dwa15-fall2018/issues/12) in which @susanBuck had troubleshooted and ultimately found the solution to which she points in the Troubleshooting section of the [Github (SSH Keys)](https://hesweb.dev/e28/notes/git/github) of the notes. 

Unfortunately, that solution did not work for me. Lower on that thread though, I found two comments by [ClericPy ](https://github.com/susanBuck/dwa15-fall2018/issues/12#issuecomment-538237632) and [LoveSponge](https://github.com/susanBuck/dwa15-fall2018/issues/12#issuecomment-634937713) that pointed to changing the order of the SSH execution paths and replacing the default OpenSSH.

I could not figure out how to change the order of the Environment Variables as the SSH paths were not within the system's environment variables, but since I had both git and Cmder, I just figured I would uninstall OpenSSH per LoveSponge. LoveSponge suggests installing `OpenSSH_8.2p1, OpenSSL 1.1.1e 17 Mar 2020`, but I did not have the time or energy to do that, and everything worked fine once I completed the uninstall using git or Cmder.

**Additional context**
Just FYI, when I enter `where SSH` into Cmder, I now get:

```
C:\Program Files\Git\usr\bin\ssh.exe
C:\cmder-master\vendor\git-for-windows\usr\bin\ssh.exe
```

Prior, the list was

```
C:\WINDOWS\System32\OpenSSH\ssh.exe
C:\Program Files\Git\usr\bin\ssh.exe
C:\cmder-master\vendor\git-for-windows\usr\bin\ssh.exe
```

**Comment by susanBuck** [comment]
Thanks for sharing this info, @katz2row.

Interestingly, my Window's machine is listing `C:\WINDOWS\System32\OpenSSH\ssh.exe` first, but I'm not having the permission issue. 

I'm going to bookmark this thread to have on my radar for future semesters in case other students have the same problem.

**Comment by susanBuck** [comment]
Going to close this thread, but anyone else have suggestions/issues with their SSH config on Windows, let mek now!
