### ISSUE TITLE
Bonus/optional material: hesweb utils

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-spring21#12]
Hi everyone,

When I had you create your course repositories, I had you use a template I provided ([susanBuck/eX](https://github.com/susanBuck/eX)). In this template, I included a bash script called *utils* that provides shortcuts for many of the sys-admin related tasks we have to do when managing our servers.

If interested, [here is a video explaining how to use these utils...](https://www.youtube.com/embed/VACUFUjEUho?rel=0&showinfo=0)

[And the accompanying notes can be found here...](https://hesweb.dev/e28/notes/misc/utils)

As I indicate in the video and notes, this script is considered in "beta" so I welcome any feedback or notes on issues you face when using it. It's also not required that you dig into this material or use the script - just throwing it out there for those that are interested.

**Comment by richiecarey** [comment]
Hi @susanBuck .. the link to the notes seem to return a permissions error ...

---
Access Denied
Your Github username has not been authorized to view secure content for this course; please email susanbuck@fas.harvard.edu if you believe this is a mistake.
← Return to https://hesweb.dev/e15
---

Thanks,
Richie
-

**Comment by susanBuck** [comment]
Hi @richiecarey -

Apologies for that - I just updated the link so it should now work for students enrolled in this course: https://hesweb.dev/e28/notes/misc/utils

Thanks for drawing my attention to this!
