### ISSUE TITLE
:key and triggering a transition

### ISSUE THREAD

**Issue by jaredmimms** [susanBuck/e28-spring21#13]
I do not understand `:key` from the [Vue.js documentation](https://v3.vuejs.org/guide/list.html#maintaining-state). What does it mean to trigger a "transition" in the [API documentation](https://v3.vuejs.org/api/special-attributes.html#key)?

**Comment by susanBuck** [comment]
Hi @jaredmimms -

You can read more about the transitions it's referring to here:
https://v3.vuejs.org/guide/transitions-enterleave.html#transitioning-single-elements-components

Transitions are elements we can use in Vue to animate the appearance/disappearance of elements in the DOM.

The example they give in the docs is this:

```html
<div id="demo">
  <button @click="show = !show">
    Toggle
  </button>

  <transition name="fade">
    <p v-if="show">hello</p>
  </transition>
</div>
```

The above example would operate such that when `show` toggles to _true_, that "hello" paragraph will transition in.
When `show` toggles to _false_, the "hello" paragraph will transition out.

How the transition works is defined via CSS. For example, here's the CSS they give for a fade transition:

```css
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.5s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
```

Let me know if you have any follow-up questions about this.

**Comment by susanBuck** [comment]
Going to close out this thread, but feel free to re-open if you have any follow-up questions.
