### ISSUE TITLE
Misc. Vue news

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-spring21#18]
Hi everyone,

This morning I was going through the [latest newsletter](https://news.vuejs.org/issues/191) from [news.vuejs.org](https://news.vuejs.org) and saw two things I thought were interesting/wanted to share:

1) A useful article that explains why Vue 2 and Vue 3 use two different approaches to set up a new Vue instance: [The Benefits of the New Vue 3 App Initialization Code](https://vueschool.io/articles/vuejs-tutorials/the-benefits-of-the-vue-3-app-initialization-code)

2) [NASA is using Vue to drive their mission control system](https://github.com/nasa/openmct):

> Open MCT (Open Mission Control Technologies) is a next-generation mission control framework for visualization of data on desktop and mobile devices. It is developed at NASA's Ames Research Center, and is being used by NASA for data analysis of spacecraft missions, as well as planning and operation of experimental rover systems. As a generalizable and open source framework, Open MCT could be used as the basis for building applications for planning, operation, and analysis of any systems producing telemetry data.

Hope everyone has a nice week,

Susan

**Comment by oms210** [comment]
NASA has been in the news lately and now this. Wow!

**Comment by oms210** [comment]
I have found Vue3 very similar in syntax to AngularJS' (the very first version).
