### ISSUE TITLE
Method called by setInterval broke when adding component?

### ISSUE THREAD

**Issue by kerynegan** [susanBuck/e28-spring21#20]
_Very much hoping that this is an actual thing and not that I've broken my code with a typo I'm just not seeing._

**Repository URL**
I am adding a few links here:

- [Overall Github link to project](https://github.com/kerynegan/e28/tree/main/p1)
- [Github commit that last worked, which I double-checked just now is working in local](https://github.com/kerynegan/e28/commit/a6537ac2ced4aa790b93bdae9079acc49c9aaed4/p1)
- [Github commit that broke my code, not in production](https://github.com/kerynegan/e28/tree/d651cd59c7dd78a6bd2dfdc235cbb20f9d9cdedf/p1)

**Production URL**
[Production link for working code, from yesterday's last commit](http://e28p1.kerynegan.me/)

**Describe the problem**
I use Chrome on a MacBook, if that matters.

Somewhere between commenting my code and adding a game-history component (essentially the rounds-detail from the class example), I broke the method for the computer's Turn (computerTurn()). 

That computerTurn() method is called by a setInterval in the changeTurn() method, to delay it so the player can see the results of their own turn before the computer makes their turn. As you can see from the production server, this was working until this afternoon when I added some comments and styling and set up the game-history component.

In the console, the interval appears to be working (it keeps getting called at 1.5 second intervals because the code doesn't progress enough to clear the interval) but the console gives me a TypeError:

> script.js:105 Uncaught TypeError: app.computerTurn is not a function at script.js:105

Attaching a screenshot of my console of the error at the bottom here.

**To Reproduce**
Steps to reproduce the behavior on the bad-commit:
1. Enter your name; then values for the range; then choose 1, 2, or 3 and press submit.
2. In the right column, under Game Tally, you should see that your turn has worked by subtracting your selection from the total. Above the player's selections, it should then say "The computer is thinking..." 
3. In production, after 1.5 seconds, the computer should make a selection, printing their move to the Game Tally. But in the bad-commit, I get the error in the screenshot below.

<img width="1451" alt="Screen Shot 2021-03-19 at 5 03 20 PM" src="https://user-images.githubusercontent.com/35839424/111844401-5c22d700-88d9-11eb-9070-80f67d00da23.png">

**Comment by susanBuck** [comment]
Hi @kerynegan -

I suspect the issue is that the reference to _app.computerTurn_ within the setInterval is not working because *app* is not recognizable within the context of that function:

```js
changeTurn() {
            if (this.turn == this.playerName) {
                this.message = "The computer is thinking..."
                this.turn = "The computer";
                this.myInterval = setInterval(function () { app.computerTurn(); }, 1500); // ←
            } else {
                this.message = "Your turn! Play a number:"
                this.turn = this.playerName;
            }
        },
```

To address this, try using an arrow function, as arrow functions will inherit their parent functions context:

```js
changeTurn() {
            if (this.turn == this.playerName) {
                this.message = "The computer is thinking..."
                this.turn = "The computer";
                this.myInterval = setInterval(() => { app.computerTurn(); }, 1500); // ← Uses an arrow function
            } else {
                this.message = "Your turn! Play a number:"
                this.turn = this.playerName;
            }
        },
```

Explanation: https://javascript.info/arrow-functions#arrow-functions-have-no-this (in this context *app* and *this* are equivalent)

If that doesn't do the trick, let me know and I can do a deeper dive.

**Comment by kerynegan** [comment]
@susanBuck Thank you so much! That didn't work, but based on the link you provided, I switched in this.computerTurn(); instead of app.computerTurn(); with that arrow notation, and it did work.

```javascript
changeTurn() {
     if (this.turn == this.playerName) {
         this.message = "The computer is thinking..."
         this.turn = "The computer";
         this.myInterval = setInterval(() => { this.computerTurn(); }, 1500);
     } else {
          this.message = "Your turn! Play a number:"
          this.turn = this.playerName;
     }
},
```
Is there a better way to do this, in Vue? I wondered about the lifecycle hooks, but wasn't sure I wanted to try messing around with them within the context of project 1.

**Comment by susanBuck** [comment]
Hi @kerynegan - Glad that got things working. 👍

(I was mistaken to say that _app_ and _this_ are equivalent - the app variable does not yet exist when the Game object is being defined.)

I'd say setInterval is the right tool for the job. I don't think lifecycle hooks would be applicable to what you're trying to accomplish here.
