### ISSUE TITLE
Browser Caching Issues

### ISSUE THREAD

**Issue by jaredmimms** [susanBuck/e28-spring21#21]
**Environment**
Production Server

**What operating system are you using?**
Mac, Ubuntu

**Describe the problem**
My Google Chrome browser cached my older script.js file for my Project 1.

**Steps taken**
I deleted my cache.

**Additional context**
I am worried about caching of my projects and want a solution to avoid caching in browser in case I want the browser to reflect changes immediately.

**Comment by acomjean** [comment]
Sometimes for files you we append a "get" string to the end when you deploy to force the browser to get the new file.  (It works with images). (Sometimes we put the date in there, which is easier when you generate you web pages dynamically).  Caching can happen so many places but this seems to always work.  Put the version number in the query string (or the updatedate)

https://stackoverflow.com/questions/32414/how-can-i-force-clients-to-refresh-javascript-files

**Comment by bryonjustice** [comment]
A simple way (albeit tedious) is to rename the javascript file and update the `<script>` src attribute.  

On the Apache server (in the htaccess file) you can configure cache headers (cache-control and/or expires).
[developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control )

**Comment by susanBuck** [comment]
My preferred approach is the method @acomjean suggested.

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any questions are still pending.
