### ISSUE TITLE
Project 1 share thread

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-spring21#22]
Hi everyone,

I wanted to start a thread where you all could share your Project 1's and check out what everyone created.

In reply to this thread, please share the following:

+ The link to your P1 on production (so everyone can view it)
+ The link to your P1 on Github (so we can see the code behind it)
+ (Optional) Any additional notes you'd like to share about your experience building the project (if you ran into any problems, novel ways of doing something, etc.)

**Comment by keamarg** [comment]
OK, here goes:

Production: [](http://e28p1.hesdev.com)

Github: [](https://github.com/keamarg/e28/tree/main/p1)

Not really a Vue issue as such, but I had some difficulties making the API's I use play well together. You might experience this as an odd coupling og words and images in the game at times.

(I use a random word API together with a random image API (unsplash), which means, that when searching for eg. "bat", sometimes the unsplash API will return a picture of an animal, and sometimes of a baseball game. I had no luck coupling more than one query to narrow the field, as the API would only take one search query for random images.)

**Comment by susanBuck** [comment]
@keamarg - I know the computer's guess is random and on a set timer, but it always makes me feel like I'm behind when it answers first. 😂

**Comment by acomjean** [comment]
I redid a prisoners dilemma simulator.

-  [production](http://e28p1.aramcomjean.com/)
- [github](https://github.com/acomjean/e28/tree/main/p1)
- I used tables for the score, which require slightly difficult handling in Vue.   I programmed 4 opponent algorithms ( very simple ones), It would be nice to have have the computer play against itself as well  and compare total scores or each algorithm vs the human player.   I still struggle with CSS but do like flexbox.

**Comment by richiecarey** [comment]
**Rock, Paper, Scissors**

- [Production](http://e28p1.richiecarey.com/)

- [Github](https://github.com/richiecarey/e28/tree/main/p1)

**Comment by kerynegan** [comment]
These are great!

I redid my **One, Two, Three** game from last time. 

- [Production](http://e28p1.kerynegan.me/)
- [Github](https://github.com/kerynegan/e28/tree/main/p1)

**Comment by seanbollin** [comment]
[Production](http://e28p1.sean-bollin.com/)
[Github](https://github.com/seanbollin/e28/tree/main/p1)

**Comment by nverno** [comment]
I did an interface to practice typing speed.

[production](http://e28p1.nverno.me/)
[github](https://github.com/nverno/e28/tree/main/p1)

**Comment by susanBuck** [comment]
@nverno - I thought this was really interesting - I've never seen a typing practice app that focussed on coding/special characters. Plan on sharing your inspiration, https://typing.io, with future students.

**Comment by oms210** [comment]
Here is mine:
[Production](http://e28p1.oms210.me/)
[Github](https://github.com/oms210/e28/tree/main/p1)

**Comment by misskimdo** [comment]
@nverno Super neat! Took me back to the Mavis Beacon Teaches Typing days. 

I also redid my Rock Paper Scissors game:
[Production](http://e28p1.kimdo.me/)
[Github](https://github.com/misskimdo/e28/tree/main/p1)

**Comment by EkaterinaMolchanova** [comment]
here is mine  - adding to 100 

[Production](http://e28p1.katemolchanova.me/)
[Github](https://github.com/EkaterinaMolchanova/e28/tree/main/p1)

**Comment by agt25** [comment]
Ahh, great job everyone! Don't mind me if I lurk and go through your GitHub code. I always find it so fascinating how projects come to be :) 

Here's my [production](http://e28.p1.vue28.me/) version of Stonks! 
...and [GitHub](https://github.com/agt25/e28/tree/main/p1) code

**Comment by bryonjustice** [comment]
Great work everyone.

[Production](http://e28p1.vueoftheyard.com/)
[GitHub repo](https://github.com/bryonjustice/e28/tree/main/p1)

**Comment by katz2row** [comment]
I like to think of this as a marathon, not a sprint. So here is my late submission.

[Production](http://e28p1.katz2row.me/)
[GitHub Repo](https://github.com/katz2row/e28/tree/main/p1)
