### ISSUE TITLE
Week 9 exercise. What strategy should I use?

### ISSUE THREAD

**Issue by keamarg** [susanBuck/e28-spring21#23]
**Repository URL**
https://github.com/keamarg/e28/tree/main/zipfoods

**Describe the problem**
After a few different strategies, I managed to solve the two first steps of the week 9 exercise. Although it is working, I am very much in doubt whether this is the intended approach. I have just started working on step 3, and this confirms my suspicion that maybe I use the wrong strategy. To be more specific, I am in doubt about how streamlining the ProductsPage.vue can change what is displayed using ShowProduct.vue.

Is it because I am using the wrong approach?

Just sharing my ProductPage.vue code here (there are no error messages):

```html
<template>
  <div id="product-page">
    <template v-for="product in products">
      <show-product
        v-if="product.id == id"
        v-bind:key="product.id"
        v-bind:product="product"
      ></show-product>
    </template>
    <span v-if="id > 10">
      <p>Product {{ id }} not found</p>
      <a href="/products">Back to products page</a>
    </span>
  </div>
</template>

<script>
import ShowProduct from "@/components/ShowProduct.vue";
import { products } from "@/common/products.js";
export default {
  props: {
    id: {
      type: String,
    },
    name: {
      type: String,
    },
  },
  components: { "show-product": ShowProduct },
  data() {
    return {
      products: products,
    };
  },
};
</script>
  
<style>
</style>
```

**Comment by susanBuck** [comment]
Hi @keamarg -

There are different ways you could go about doing this:

**Option 1)** Don't try to use the _ShowProduct_ component for both the _ProductsPage_ and _ProductPage_ since they both need to display different information. Maybe _ProductsPage_ doesn't even need a child component to display the info it needs - maybe it just embeds the info directly.

**Option 2)** Add a prop to the _ShowProduct_ component that can be used to customize what information it displays. For example, maybe there's a _showDetailed_ prop that when _true_, includes all the details (name, image, description, price), but when _false_ it only displays the name and image.

Then, when _ProductsPage_ uses _ShowProduct_, it'd set _showDetailed_ to _false_.
But when _ProductPage_ uses it, it'd set _showDetailed_ to _true_.

**Comment by keamarg** [comment]
Thanks. I was already going down the "option 2" path, and I think I got it working OK now.

Just one more question. I am trying to get the <router-link> to wrap the whole <div> only if I am on the ProductsPage. It kinda works, but the problem is, that the product on ProductPage is then not displayed, because the elements inside my <router-link> tag are not rendered. If I do not give the <router-link> element the v-if directive, the product on the ProductPage is also wrapped as a link, which I would like to avoid as it does not make sense on that page.

In short, is there any way to render the elements inside the <router-link> on the ProductPage, without having the enclosing <router-link> tag itself being rendered? I guess I could just make an v-else statement and copy all the nested elements, but that seems redundant. Maybe there is a better solution?

It is a bit hard to explain, but I hope you understand what I mean;)

```html
<template>
  <div class="show-product">
    <router-link
      v-if="!showProductDetails()"
      v-bind:to="'/products/' + product.id"
    >
      <div class="name">{{ product.name }}</div>

      <img
        class="thumb"
        v-bind:src="require('@/assets/images/products/' + product.id + '.jpg')"
      />

      <div v-if="showProductDetails()" class="price">${{ product.price }}</div>
      <p v-if="showProductDetails()" class="description">
        {{ product.description }}
      </p>
    </router-link>
  </div>
</template>

<script>
export default {
  props: {
    product: {
      type: Object,
    },
  },
  methods: {
    showProductDetails() {
      return this.$route.fullPath !== "/products";
    },
  },
};
</script>
```

Thanks for the quick help:)

**Comment by susanBuck** [comment]
I suggest not putting _<router-link>_ inside the _ShowProduct_ component but instead use it when invoking the _ShowProduct_ component when you want it to be a link.

E.g. in the all products page you'd use it like this:

```html
<router-link v-for....>
    <show-product></show-product>
</router-link>
```

But in the individual product page you'd just do:

```html
<show-product></show-product>
```

If you didn't want to go this path and really wanted the _router-link_ to be part of the _ShowProduct_ component, [here are some other creative solutions to conditionally render the router-link](https://stackoverflow.com/questions/44829965/conditional-router-link-in-vue-js-dependant-on-prop-value/55368379), but they're all a little messy, IMO.

**Comment by keamarg** [comment]
Great, thanks again😀

**Comment by susanBuck** [comment]
You're welcome! : )
