### ISSUE TITLE
Week 9 Question 2 404 Issue

### ISSUE THREAD

**Issue by jaredmimms** [susanBuck/e28-spring21#24]
I clicked on the link in Question 2 from Week 9 on the assignment preview and got a 404 not found message. I had to go through the notes manually to find the section detailing the exercise.

**Comment by susanBuck** [comment]
Hm, weird, not getting a 404 error on my end.

To make sure we're on the same page, you are talking about this link: 
![image](https://user-images.githubusercontent.com/237711/113761601-a5e72c00-96e5-11eb-98a2-617ed0555b34.png)

... yes?

On my end it points to https://hesweb.dev/e28/notes/vue/vue-router#exercise which loads. Can you tell me if it's pointing to a different URL on your end?

**Comment by katz2row** [comment]
It worked for me without a 404.
