### ISSUE TITLE
Availability of Wk 10 Lecture Videos and Assignment Materials  

### ISSUE THREAD

**Issue by bryonjustice** [susanBuck/e28-spring21#25]
It appears that some week 10 lectures (Part 6 and 7) are still processing and the assignment was not posted.  I typically watch when the materials open but stopped last night once I completed what was available. At 1:00pm US Eastern Wednesday, April 7 it is still pending.  I wanted to share for awareness.

**Comment by susanBuck** [comment]
Hi Bryon,

Apologies for the delay. Had some data corruption problems and I lost several hours of work on the last recordings. Working on rebuilding them now and will get them posted ASAP (Part 6 is about to be posted, Part 7 coming soon).

The assignment should have been posted last night - didn't realize until now that it wasn't so thank you for drawing my attention to that. It's posted now.

Thanks for your patience with this. It's been one of those weeks. :-)

**Comment by susanBuck** [comment]
Every thing is posted now so I'll close out this thread. Thanks again, @bryonjustice.
