### ISSUE TITLE
Commas in a JSON array as separator v. punctuation

### ISSUE THREAD

**Issue by misskimdo** [susanBuck/e28-spring21#26]
When creating my seeds JSON list, how do I correctly differentiate between a comma as a separator v. a punctuation in my recipe directions list?

**I tried:**
```
"directions": ["Peel and finely mince the garlic.","Finely chop the green onions.","In a measuring cup: add the sesame oil, lemon juice, soy sauce, oyster sauce, and sugar."]
```
No errors come up, but this doesn't show up on the dashboard.

**I'm also trying**
```
"directions": "Peel and finely mince the garlic.,Finely chop the green onions.,In a measuring cup: add the sesame oil, lemon juice, soy sauce, oyster sauce, and sugar.
```
**Expected outcome when I later split the array**
- Peel and finely mince the garlic.
- Finely chop the green onions.
- In a measuring cup: add the sesame oil, lemon juice, soy sauce, oyster sauce, and sugar.

**Comment by susanBuck** [comment]
Instead of separating the directions by a comma, try a character that you know won't be part of the directions, e.g. a pipe character `|`. Then you can do `directions.split("|")`.

**Comment by misskimdo** [comment]
Got it. Thank you!
