### ISSUE TITLE
Week 2 practice assignment share thread

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-spring21#3]
Hi everyone - In this thread I encourage you all to share the links to JSFiddles for the games you created as part of your Week 2 assignment.  This way your classmates can check out what you made, and vice versa. 

We often get a lot of the same games in this task (e.g. lots of rock, paper, scissors), so it can be interesting to look at the varied approaches to the same program.

**Comment by misskimdo** [comment]
Hi, all! Here's my version of [Rock, Paper, Scissors](https://jsfiddle.net/kim_do/tdgwcrse/3/)

**Comment by agt25** [comment]
Loved Kim's game — especially the "it's a {tie emoji}!"

Here's mine [Stonks](https://jsfiddle.net/agtt25/0mcfu1L2/11/)

**Comment by EkaterinaMolchanova** [comment]
My [Hi-Low](https://jsfiddle.net/emolchanova/fe1p7Lsx/)

**Comment by millierni** [comment]
I made a game based on the Bitcoin!
The game is a simplified version of what miners does in real life (Proof of work).
[Mine The Hash](https://jsfiddle.net/tpzdo1gq/)

**Comment by oms210** [comment]
Here's mine. Very basic. [Race 2 Five] (https://jsfiddle.net/oms210/kyL32zp9/3/)

**Comment by keamarg** [comment]
> Loved Kim's game — especially the "it's a {tie emoji}!"
> 
> Here's mine [Stonks](https://jsfiddle.net/agtt25/0mcfu1L2/11/)

Haha, I love how the gameplay and UI with hidden stocks also conveys how random the stockmarket really is...

**Comment by agt25** [comment]
> And here is mine... [Guess the closeup](https://jsfiddle.net/magu/aukfy21r/) (you may have to stretch the fiddle a bit as the css is very basic).
> 
> > Here's mine [Stonks](https://jsfiddle.net/agtt25/0mcfu1L2/11/)
> 
> Haha, I love how the gameplay and UI with hidden stocks also conveys how random the stockmarket really is...

Ah, ultimately, it is all glorified gambling; it is the kind you _can_ win in if you play your cards right and diversify. But nothing is ever risk-averse. Some stocks, like half the losers I included, will just say (to quote Guess the closeup!) "sorry but nope". Great job! Got me a few times :wink:

**Comment by richiecarey** [comment]
[Rock, Paper, Scissors](https://jsfiddle.net/richiecarey/axbtj02d/)

**Comment by kerynegan** [comment]
These are all so good! 

Here's mine: [One, Two, or Three](https://jsfiddle.net/kerynegan/5dgobeua/).

**Comment by misskimdo** [comment]
> These are all so good!
> 
> Here's mine: [One, Two, or Three](https://jsfiddle.net/kerynegan/5dgobeua/).

I like it when the computer's sassy: "You have to start the game first, pal!" 😆

**Comment by acomjean** [comment]
I did a  "Prisoner's Dilemma" game, where you play against the computer.

https://jsfiddle.net/acomjean/dju2wq7r/

**Comment by trevjburns** [comment]
> Loved Kim's game — especially the "it's a {tie emoji}!"
> 
> Here's mine [Stonks](https://jsfiddle.net/agtt25/0mcfu1L2/11/)

This is awesome! 💎🙌

Here's my simple number guessing game: [https://jsfiddle.net/trevjburns/egj9t0mn](https://jsfiddle.net/trevjburns/egj9t0mn)

**Comment by bryonjustice** [comment]
Rock - Paper -Scissors

https://jsfiddle.net/BryonJustice/by9quvja/

**Comment by jaredmimms** [comment]
[Wac-A-Virus](https://jsfiddle.net/jmimms/rdcpskjh/)

**Comment by katz2row** [comment]
Here is my [Rock, Paper, Scissors](https://jsfiddle.net/katz2row/faLjwnbk/8/).

Now if I can just get things done more timely. Oy!

**Comment by dan-harnden** [comment]
Feel free to fool with my self degradation quiz and random answer generator game...

[https://jsfiddle.net/8rh4ay9q/](url)

**Comment by dan-harnden** [comment]
[https://jsfiddle.net/8rh4ay9q/](url)

**Comment by susanBuck** [comment]
These were all great - thanks for sharing everyone.

I wanted to take a moment to give a "shout-out" to some of my favorites before closing this thread:

+ @acomjean https://jsfiddle.net//dju2wq7r Always enjoy a good prisoner's dilemma simulation
+ @kerynegan https://jsfiddle.net/kerynegan/5dgobeua Thought the logic of this number game was pretty creative
+ @millierni https://jsfiddle.net/tpzdo1gq I only partially understand bitcoin/mining, but still found this game interesting : )
+ @trevjburns https://jsfiddle.net/trevjburns/egj9t0mn I liked the graphical interface on this number guessing game
+ @nverno https://jsfiddle.net/nverno/5mdyq1hs/1 I like how this hangman game taps into an external API
+ @agt25 https://jsfiddle.net/agtt25/0mcfu1L2/11 _"Today you'd be worth $611,284 had you invested in Amazon, 2009."_ 😩
