### ISSUE TITLE
XAMPP not hosting API

### ISSUE THREAD

**Issue by jaredmimms** [susanBuck/e28-spring21#30]
**Environment**
Local Server

**What operating system are you using?**
Mac

**Describe the problem**
XAMPP hosting of API does not work despite following configuration steps 

**Steps taken**
My 
/Applications/XAMPP/etc/extra/httpd-vhosts.conf
```
<VirtualHost *:80>
    ServerName e28api.jaredmimms.loc
    DocumentRoot "/Applications/XAMPP/xamppfiles/htdocs/e28/e28api/core/public"
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e28/e28api/core/public>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs
    <Directory /Applications/XAMPP/xamppfiles/htdocs>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>
```

My
/private/etc/hosts
```
127.0.0.1       e28api.jaredmimms.loc
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
```

**Additional context**
http://e28api.jaredmimms.loc goes to the XAMPP welcome page.

**Comment by susanBuck** [comment]
Can you run and share the output of the command `/Applications/XAMPP/bin/httpd -S` ?

This will identify any issues/syntax errors that might exist in the VirtualHosts file.

Ref: https://hesweb.dev/e28/notes/local-server/local-domains#debugging-the-virtualhosts-file-ememhttpd-vhostsconfemem

Finally, restart XAMPP's Apache. I'm sure you've already done that, but never hurts to do it again.

**Comment by jaredmimms** [comment]
Ok thanks. I fixed it by commenting in the virtual host include in the XAMPP configuration file.
