### ISSUE TITLE
My build site works on my laptop, but not showing up on other computers.

### ISSUE THREAD

**Issue by misskimdo** [susanBuck/e28-spring21#34]
**Repository URL**
[https://github.com/misskimdo/e28/tree/main/p2](https://github.com/misskimdo/e28/tree/main/p2)

**Production URL**
[http://e28p2.kimdo.me/](http://e28p2.kimdo.me/)

**Describe the problem**
Error in console: 
```
GET http//e28api.kimdo.loc/recipe xhr.js:177
net: :ERR_NAME_NOT_RESOLVED
```

**To Reproduce**
1. Go to [http://e28p2.kimdo.me/](http://e28p2.kimdo.me/)
2. Looks like the API data isn't available, so nothing shows up.

**Additional context**
[http://e28api.kimdo.me/](http://e28api.kimdo.me/) shows up correctly

**Comment by susanBuck** [comment]
Hi @misskimdo -

It looks like your axios configs are hardcoded to point to the .loc version of your API: https://github.com/misskimdo/e28/blob/main/p2/src/common/app.js#L2

You'll need to set up an environment variable so your production build of your app points to the production (.me) version of your API.

Ref: https://hesweb.dev/e28/notes/vue/e28api-production#e28api-on-production

**Comment by misskimdo** [comment]
@susanBuck That's right! I did forget to update that. Thank you!

**Comment by susanBuck** [comment]
np!
