### ISSUE TITLE
Can I use Django for my API? 

### ISSUE THREAD

**Issue by agt25** [susanBuck/e28-spring21#35]
I've recently gained a bit of experience with Django, through another course. I was wondering if I'm allowed to use Django models for my backend/API for p3. Thus far, I've used Firebase on p2 but I would love to make the switch to Django for p3! 

Thank you,
Angela

**Comment by susanBuck** [comment]
Yup, that's fine. You can use whatever backend API you'd like.

**Comment by agt25** [comment]
> Yup, that's fine. You can use whatever backend API you'd like.

Awesome! Thank you so much!
