### ISSUE TITLE
store.js causing console error

### ISSUE THREAD

**Issue by misskimdo** [susanBuck/e28-spring21#37]
**Describe the problem**
I've created a practice version of store.js. When testing the homepage, nothing is showing up and I get an error in the console. It's pointing to line 10, but I can't make sense of why.

```
import { createCollection, createLogger } from 'vuex'
import { axios } from "@/common/app.js";

// Only load the createLogger plugin when in development mode
const debug = process.env.NODE_ENV !== 'production';
const plugins = debug ? [createLogger({})] : [];

export const collection = createCollection({
    plugins,
    state() {
        return {
            recipes: [],
        }
    },
    mutations: {
        setRecipes(state, payload) {
            state.recipes = payload;
        }
    },
    actions: {
        getRecipes(context) {
            axios.get("recipe").then((response) => {
                context.commit('setRecipes', response.data.recipe);
            });
        }
    }
});
```
**To Reproduce**
1. Go to local homepage
2. Console error output:
```
Uncaught TypeError: Object(...) is not a function
    at eval (collection.js:10)
    at Module../src/common/collection.js (app.js:1486)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (main.js:11)
    at Module../src/main.js (app.js:1786)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at Object.1 (app.js:1799)
  | eval | @ | collection.js:10
-- | -- | -- | --
  | ./src/common/collection.js | @ | app.js:1486
  | __webpack_require__ | @ | app.js:849
  | fn | @ | app.js:151
  | eval | @ | main.js:11
  | ./src/main.js | @ | app.js:1786
  | __webpack_require__ | @ | app.js:849
  | fn | @ | app.js:151
  | 1 | @ | app.js:1799
  | __webpack_require__ | @ | app.js:849
  | checkDeferredModules | @ | app.js:46
  | (anonymous) | @ | app.js:925
  | (anonymous) | @ | app.js:928
```

**Additional context**
When I installed vuex, I also got this output:
```
npm WARN postcss-modules@4.0.0 requires a peer of postcss@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN icss-utils@5.1.0 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-modules-extract-imports@3.0.0 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-modules-local-by-default@4.0.0 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-modules-scope@3.0.0 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-modules-values@4.0.0 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.

+ vuex@4.0.0
added 1 package from 1 contributor and audited 1350 packages in 6.607s

79 packages are looking for funding
  run `npm fund` for details

found 6 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by susanBuck** [comment]
@misskimdo - Can you push your latest code changes to Github so I can clone and reproduce the error on my end?

**Comment by susanBuck** [comment]
Think I spotted the bug.

Up top, you're importing `createCollection` instead of `createStore`. 

This:
```js
import { createCollection, createLogger } from 'vuex'
```

Should be:
```js
import { createStore, createLogger } from 'vuex'
```

And on line 8, this:
```js
export const collection = createCollection({
```

Should be:
```js
export const store = createStore({
```

**Comment by misskimdo** [comment]
@susanBuck That fixed it - thanks! 

But can you help me understand better - so is "store" is not a name in this situation? I think I was confused because Zipfoods is a store, so I thought I could rename it to "collection," which was more apt with my project.

**Comment by bryonjustice** [comment]
Sharing from the Vuex documentation:
"At the center of every Vuex application is the store. A "store" is basically a container that holds your application state. "

As the professor notes you would need to `import { createStore }` as a part of the standard Vuex API to create a new store.

In order to have access to `this.$store` property in your Vue components, you need to provide the created store to Vue instance. 

Good Source for additional elaboration:
[https://vuex.vuejs.org/guide/](https://vuex.vuejs.org/guide/)
[https://next.vuex.vuejs.org/api/](https://next.vuex.vuejs.org/api/)

**Comment by misskimdo** [comment]
@bryonjustice Thanks! I did see the documentation, but was definitely confused because of the coincidental nomenclature.

**Comment by susanBuck** [comment]
@misskimdo - That is coincidental nomenclature - I can see how that could be confusing. : )

We first see the use of the "store" vocabulary here: https://hesweb.dev/e28/notes/vue/add-to-cart#cart-count-simple-data-store

I've made a note to update these notes in future semester to be sure just to make the distinction between "data store" and "e-commerce store". 👍
