### ISSUE TITLE
Authentication persistence

### ISSUE THREAD

**Issue by richiecarey** [susanBuck/e28-spring21#38]
**GitHub**: https://github.com/richiecarey/e28/tree/main/p3

**Production**: http://e28p3.richiecarey.com/

----

Something is wrong with the way I've implemented authentication but I've been unable to determine the issue.

I have Navigation Guards setup on all routes other than `/account` and  users who are not authenticated are redirected to `/account`.

What's happening is this: if a user logs in, leaves, and then returns immediately to the site (or simply hard refreshes a page) the [store.state.user](https://github.com/richiecarey/e28/blob/227328026beaf6f0f87735567ed42caecdaa2141/p3/src/common/router.js#L54) value in `router.js` is null and the user is redirected to [/account](https://github.com/richiecarey/e28/blob/main/p3/src/components/pages/AccountPage.vue). However, once there, it seems that the user **is** recognized.

It's not clear to me why the user is _**not**_ recognized in the router but **is** recognized in the /account page.

Ultimately the goal is for a user to be able to leave the site, return to a bookmarked page, and have their auth recognized 'in page' without the extra redirect to /account

**Comment by richiecarey** [comment]
I may have resolved this by installing [vuex-persistedstate](https://github.com/robinvdvleuten/vuex-persistedstate).

**Comment by susanBuck** [comment]
Thanks for bringing this up @richiecarey - Here's another solution: https://github.com/susanBuck/e28-spring21/issues/39
