### ISSUE TITLE
Bug fix: "Access Denied" when refreshing the "Add a Product" page

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-spring21#39]
Last week, in our Vue router code we set up a **beforeEach** navigation guard to protect certain routes (e.g. _Add a Product_ route) from being accessed by non-logged in users.

```js
router.beforeEach(async (to, from, next) => {

    const requiresAuth = to.matched.some(record => record.meta.requiresAuth);

    if (requiresAuth && !store.state.user) {
        next('/denied');
    }
    else {
        next();
    }
});
```

This worked when navigating between routes, but **there was a bug where you would see the _Access Denied_ route if you refreshed the browser while on a login-required route such as *Add a Product***

This occurred because the value for `store.state.user` was not available in the _beforeEach_ guard until the app was mounted and we dispatched _authUser_ from _App.vue_:

```js
mounted() {
    this.$store.dispatch('authUser');
}
```

To address this, we should move our dispatching of *authUser* to the router *beforeEach* guard, but we want to do so in such a way that we are not attempting to authorize the user every time we visit a new route.

This can be accomplished with the following updated *beforeEach* guard:

```js
router.beforeEach(async (to) => {

    // Exact the meta information from our routes
    // Ref: https://router.vuejs.org/guide/advanced/meta.html#route-meta-fields
    const requiresAuth = to.matched.some(record => record.meta.requiresAuth);

    // Put the “decide what to do” code into a method so we can wait to invoke it
    // once we have the user data
    const decide = (user) => {
        if (requiresAuth && !user) {
            // If they’re trying to access a requiresAuth route and they’re not logged in, 
            // they get sent to “Access Denied” page
            return '/denied';
        } else {
            // Otherwise, allow them to intended destination
            return true;
        }
    }

    // If we don’t have the user yet, dispatch our Vuex authUser action
    if (store.state.user === null) {
        let authUser = await store.dispatch('authUser');
        if (authUser !== null) {
            return decide(store.state.user);
        }
    } else {
        return decide(store.state.user);
    }
});
```

Two notes about the above code:
1. Instead of using `next()` we use `return true` to send the user to their intended destination. Revisiting the docs I learned that in the latest version of Vuex, _next_ is still supported but not suggested ([ref](https://next.router.vuejs.org/guide/advanced/navigation-guards.html#optional-third-argument-next)).
2. The above code expects the dispatching of *authUser* to be a asynchronous call (see the usage of _then(...)_)

To accommodate point 2, we can adapt our *authUser* action (in `/src/common/store.js`) to return a _Promise_:

```js
authUser(context) {
    return new Promise((resolve) => {
        axios.post('auth').then((response) => {
            if (response.data.authenticated) {
                context.commit('setUser', response.data.user);
            } else {
                context.commit('setUser', false);
            }

            resolve();
        });
    });
},
```

(More details on actions returning Promises here: [Vuex: Composing actions](https://vuex.vuejs.org/guide/actions.html#composing-actions))

Other misc. changes you should make to accommodate the above updates:
1. Remove the invocation of the `authUser` action in App.vue's _mounted_ method, as that's now happening in the router _beforeEach_.
2. In AccountPage.vue's logout method, have it set the user to _false_ instead of _null_. This way we can distinguish between _"the user status is unknown"_ and _"the user status is logged out"_

I'll walk through the above fix in next week's lecture, but wanted to post this now in case anyone else noticed this bug in the interim.

**Comment by bryonjustice** [comment]
I have implemented the above fix but I am finding that even though requiresAuth is set in the meta for the route and the store.state.user is false the access to the page is still being granted even if the user is logged out.  It does not seem to be honoring the return '/denied'

```
    const decide = () => {
        if (requiresAuth && !store.state.user) {
            console.log('should redirect to denied');
            return '/denied';
        }
        else {
            console.log('user: ' + store.state.user);
            return to;
        }
```

**Comment by susanBuck** [comment]
Looking at this with a fresh set of eyes and I see what you mean, @bryonjustice. Taking a closer look now and will report back on what's going on.

**Comment by susanBuck** [comment]
@bryonjustice - I did some tweaking and edited my above post with corrected code.

I also added some E2E tests to help check all the conditions were working as expected.

![image](https://user-images.githubusercontent.com/237711/117039928-52153600-acd7-11eb-8920-9b09eb7117b1.png)
