### ISSUE TITLE
Caching Issue

### ISSUE THREAD

**Issue by sgreene** [susanBuck/e28-spring21#4]
**Environment**
Local Server

**What operating system are you using?**
Mac

**Describe the problem**
This issue stole a few minutes of my time tonight and I just wanted to raise it in case any one else ran into it. I made some changes to my game javascript and refreshed my browser expecting to see the changed reflected.  Much to my surprise it was not. I frantically started updating the code to add console.log statements but these weren't being reached either. I then noticed that older functions were being invoked fine. That's when I checked the network tab in my developer console on chrome. At first everything looked normal, but when I looked at the javascript file my browser was using, it was clearly the wrong one! An older version. I immediately realized that this was a caching issue and looking at this screenshot of my network tab you can see that too:
![Screen Shot 2021-02-09 at 8 52 23 PM](https://user-images.githubusercontent.com/545568/107453491-12e0aa00-6b19-11eb-825f-0f41468b4dde.png)

I was able to rectify the issue by clicking on the `disable cache` checkbox in the developer console. It was pretty strange that I had not noticed any caching until after I made a major change but hopefully this post is useful for anyone else having similar issues.

**Comment by oms210** [comment]
This is a very common issue with javascript. I always hit ctrl+F5 to hard-refresh a page. This forces the webpage to download a fresh copy and any associated script files. You would not need to tweak any settings in your browser.

**Comment by susanBuck** [comment]
Thanks for posting this, @sgreene. 👍 

Every semester it seems at least one student gets "bit" by the cache bug - either with their JS or CSS so it's a good reminder.
