### ISSUE TITLE
P3: State Management Requirement Clarification

### ISSUE THREAD

**Issue by agt25** [susanBuck/e28-spring21#40]
Hi Professor Buck,

I tend to overthink things so please forgive me if the following questions are rather silly! 

For project 3, the requirement for state management states: "at least one data entity of your app should be managed via a Vuex store". Is it enough that we 'get' our main data (e.g., products) using state management? Or, do we need one additional data entity aside from the main data (e.g., cart count). 

Also, is it okay if my app doesn't utilize forms? Or should I add a feature with a form (and validation) so I can meet the form validation requirement? 

Thank you,
Angela

**Comment by susanBuck** [comment]
Hi @agt25 -

Never hurts to clarify, so questions are always welcome. : )

Yup, It is enough to get/manage one data point (e.g. products). If it makes sense to put manage data in the store, you should, but it's not required.

RE: the form - You should have a login and registration form to meet the auth requirements, yah? That would count as a form if you do.

**Comment by agt25** [comment]
> Hi @agt25 -
> 
> Never hurts to clarify, so questions are always welcome. : )
> 
> Yup, It is enough to get/manage one data point (e.g. products). If it makes sense to put manage data in the store, you should, but it's not required.
> 
> RE: the form - You should have a login and registration form to meet the auth requirements, yah? That would count as a form if you do.

Ah, yes, yes! I was thinking of the "add a product" form. Thank you so much :smiley:
