### ISSUE TITLE
hosts file on Windows is not taking change for local domain

### ISSUE THREAD

**Issue by seanbollin** [susanBuck/e28-spring21#6]
**Environment**
Local

**What operating system are you using?**
Windows 10

**Describe the problem**
The virtual hosts are working in that my http://localhost/ points to the new project based directory, however editing my hosts file seems to have no effect.

**Steps taken**
I added the line:
127.0.0.1 e28p1.loc

to my hosts file here: C:\Windows\System32\drivers\etc\hosts

and it seems to have no effect. Accessing http://e28p1.loc does fails DNS lookup

**Additional context**
This is a minor problem as I can work around it by not having a local domain

**Comment by susanBuck** [comment]
Hi @seanbollin -

Can you share the output of running the command `ping e28p1.loc` ?

**Comment by susanBuck** [comment]
Just to check all our bases, also share the contents of `C:\Windows\System32\drivers\etc\hosts`.

**Comment by katz2row** [comment]
I think I got it, @seanbollin. Check the DocumentRoot and Directory. Are they point to 

`DocumentRoot /path/to/htdocs/e28/practice
 <Directory /path/tohtdocs/e28/practice>`

or 

`DocumentRoot c:\xampp\htdocs\e28\practice
 <Directory c:\xampp\htdocs\e28\practice>`

It should be the latter, and if it is the latter, check the path and make sure that is where the folder actually is. 

Also, double check that there is a file in that location. If not the starter files you are using on GitHub, at minimum an index.html or index.php file or you'll get a forbidden response.

**Comment by seanbollin** [comment]
Thanks for the feedback. Looks like I was having issues getting changes to my hosts file to persist - let me try that again

**Comment by susanBuck** [comment]
@seanbollin  -

Gotcha. Just a reminder the hosts file is admin protected so editing it requires `sudo` (Mac/Linux) or `elevate` (Windows).

E.g.: Mac:

```
sudo nano /etc/hosts
```

E.g. WIndows:
```
elevate nano c:\Windows\System32\drivers\etc\hosts
```
