### ISSUE TITLE
Chrome extension warning in dev console with Vue

### ISSUE THREAD

**Issue by sgreene** [susanBuck/e28-spring21#7]
**Environment**
Local Server, Chrome Browser.

**What operating system are you using?**
Mac

**Describe the problem**
When I load the simple intro script.js from notes I see a warning about DevTools failing to load a source map in the console. Here's what the message looks like:

![Screen Shot 2021-02-14 at 5 11 12 PM](https://user-images.githubusercontent.com/545568/107890571-b3531780-6ee7-11eb-9408-0aa82cf30170.png)

I did some Googling and found a [related question on SO](https://stackoverflow.com/questions/60302529/devtools-failed-to-parse-sourcemap-chrome-extension) . [This answer ](https://stackoverflow.com/a/60524615/636131) worked for me.
It may have something to do with the Macafee extension or some other conflicting extension. 

**Steps taken**
* Replicated the intro Vue.js project from notes.
* Loaded index.html in Chrome browser.

**Additional context**
This may be related to a Macafee Web Agent or related security extension. Unfortunately I can't remove this extension (company policy) but nice to know there's a simple workaround.

**Comment by susanBuck** [comment]
Thanks for sharing, @sgreene. Glad you found a work-around; having that warning there - even though I knew it wasn't actually impacting any of my work - would still bug me. : )

**Comment by acomjean** [comment]
I get the same thing in firefox.  Looks like its my password manager.  I'll try the fix.  
The Vue.js toolbar reports a lot to the console.  But no other errors for me.  

I get redirects when loading Vue from the CDN but it does work.

![vue js](https://user-images.githubusercontent.com/3139639/108022553-c270bd00-6fee-11eb-9b99-ab61af4368c9.png)

**Comment by susanBuck** [comment]
@acomjean - I looked into all that console output from the Vue devtools beta build, and will speak to it in Part 1 of the lectures I'll post today. 

Long story short, it's just because of the beta build. Reference: [Excessive logging in console (v6.0.0-beta.6)](https://github.com/vuejs/vue-devtools/issues/1359)

**Comment by susanBuck** [comment]
I've noticed recent builds of the dev tools don't have the excessive longing anymore. 👍
