### ISSUE TITLE
Permission denied when saving httpd-vhosts.conf file

### ISSUE THREAD

**Issue by misskimdo** [susanBuck/e28-spring21#8]
**Environment**
Local server

**What operating system are you using?**
MacOS Big Sur, Version 11.2.1

**Describe the problem**
I am able to access and edit the httpd-vhosts.conf file, but cannot save due to: "Error writing /Applications/XAMPP/xamppfiles/etc/httpd.conf: Permission denied"

**Steps taken**
I've tried accessing the permissions and updating manually, but access was also denied there. 

I also tried ``` sudo chmod -R 777 /Applications/XAMPP/htdocs/ ``` within Terminal.

**Additional context**
None

**Comment by susanBuck** [comment]
Hi @misskimdo -

The error you shared references the Apache config file, `httpd.conf`.

Are you trying to edit that file, or your Apache Virtual Hosts config file (`httpd-vhosts.conf`) ?

Regardless, share the output of the following 2 commands so we can see the current permissions on both these two files:

```bash
$ ls -la /Applications/XAMPP/xamppfiles/etc/httpd.conf
```

```bash
$ ls -la /Applications/XAMPP/etc/extra/httpd-vhosts.conf
```

Regardless of the permissions, prefixing your edit command with `sudo` should get you around any permission issues, as it will initiate the edit as an admin. E.g.:

```bash
$ sudo nano /Applications/XAMPP/etc/extra/httpd-vhosts.conf
```

**Comment by misskimdo** [comment]
Hi, @susanBuck 

```
-rw-r--r--  1 root  admin  18900 Feb 10 18:05 /Applications/XAMPP/xamppfiles/etc/httpd.conf
```
```
-rw-r--r--  1 root  admin  1491 Jan 12 13:18 /Applications/XAMPP/etc/extra/httpd-vhosts.conf
```

I'm attempting 
> Step 1: Tell Apache to use the virtual hosts file
First, locate and open httpd.conf, your local server’s Apache configuration file:
Mac: /Applications/XAMPP/xamppfiles/etc/httpd.conf

**Comment by susanBuck** [comment]
ok - it does appear your Apache config file (httpd.conf) is owned by your root/admin user.

If you open the file using sudo (effectively as "root"), you should be able to save your changes. E.g.:

```bash
$ sudo nano /Applications/XAMPP/xamppfiles/etc/httpd.conf
```

If that doesn't do the trick, let me know!

**Comment by misskimdo** [comment]
Yes, prefixing `sudo` worked. Thanks so much!
