### ISSUE TITLE
Using Pandoc to Convert To and From Markdown

### ISSUE THREAD

**Issue by katz2row** [susanBuck/e28-spring21#9]
We use markdown at my work for some of our lab guides and other documents. These are long 60+ page documents (in Word) with a lot of images and formatting. Not everyone on my team knows how to write in Markdown, nor do they have the time to learn. My team only uses it really once a year at this point. So we do edits in Word, which also helps when working cross-team, and then convert the Word documents to Markdown. 

Last year I discovered Pandoc, which is a lightweight, free download. It allows you to easily convert to and from Markdown. A properly styled Word document, and the images, can be converted into a full Markdown file, which can then just be loaded to GitHub. 

I am not sure to what extent we will ultimately be using Markdown in this course, but I thought I would pass this tip on. 

[https://pandoc.org/index.html](https://pandoc.org/index.html)

**Comment by susanBuck** [comment]
Excellent resource, @katz2row - thanks for sharing!

**Comment by katz2row** [comment]
It is pretty awesome with what it supports, and it doesn't have to be to and from Markdown. You can use it to convert between other file types as well, but for my purposes, Markdown is the most important. 

It takes some digging but there are additional commands that can be used in the conversion that help do things like extract the images, which made my work a lot easier. What was really awesome, though, was that after doing the conversion and adding the Markdown to GitHub, we found a few other places we needed to make edits for clarity. After all was said and done, I was able to extract all of the files from GitHub as a ZIP file, and then convert the Markdown file to a Word document, which I could send to the Business Unit to edit since they didn't know Markdown, and so we aren't losing the edits we made in Markdown. 

For me, from a work perspective, it gave me the power to do the work I needed on my own time and at any time of the day rather than taking a 60+ page, heavily-styled document and having to rely on a 3rd party to do the conversion or spending a crazy amount of hours doing it. With our conference coming up this year (and actually going live on our last day of this class) and potentially 3-4 classes for which I'll be responsible (which is more than just the guide), I am thrilled that I had found this resource last year, and I am actually preparing a quick "brown bag" session to teach it to our larger team for those who want the power themselves.

**Comment by susanBuck** [comment]
Sounds awesome - have to love when you land on a great tool that makes your life so much easier. : )
